"""empty message

Revision ID: a157842e3a79
Revises: 459bb558add8
Create Date: 2025-08-27 16:55:54.886669

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a157842e3a79'
down_revision: str | Sequence[str] | None = '459bb558add8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geodata', sa.Column('display_name', sa.String(), nullable=False))
    op.drop_column('geodata', 'displayed_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geodata', sa.Column('displayed_name', sa.VARCHAR(), nullable=False))
    op.drop_column('geodata', 'display_name')
    # ### end Alembic commands ###
