services:
  web-app:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: "fastapi run src/app/server.py --reload "
    container_name: geocoding-app
    ports:
      - "${SERVER_PORT}:8000"
    env_file:
      - .env
    volumes:
      - .:/app/
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: postgresdb
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: